# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

gems:
  - jekyll-paginate
  - jekyll-sitemap
  # Font Awesome GEM // UNUSED // see _includes/head.html
  #- font-awesome-sass

# Setup
title: fabic

tagline: |
    random (binary) wanderings
    in the philament empires&hellip;

description: |
    if (fail); then
      try:
        // ...
      catch( again ):
        // fixme: this ain't the proper way
        // fixme: of handling this error
        // fixme: condition; we can do better.
        throw again;



#just killing time, from a shell&hellip;

url:                 http://blog.fabic.net
baseurl:             ""
paginate:            5

# Comments are powered by disqus
comments: false

# Google analytics
#   ( https://analytics.google.com/
#     see _includes/analytics.html
#     which is included by _layouts/default.html )
#
tracking_id: UA-69243698-7 # GA Tracking ID

# About/contact
author:
  name:              Fabien Cadet
  url:               http://fabic.net
  email:             cadet.fabien@gmail.com

# Custom vars
version:             v1.0.1

twitter_username: FabienKd

github_repo: fabic.github.com
github_username: fabic
github_show_edit_link: true

flickr_username: fabicxx
#facebook_id: yourusername
