# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems:
  - jekyll-paginate
  - jekyll-sitemap

# Setup
title: Maty
tagline: |
    Senior Compositing Artist,
    Technical Director
    & Pipeline Developer

description: |
    Senior Compositing Artist, Technical Director & Pipeline Developer
    at <a href="http://nWave.com" target="_blank">nWave Digital</a> (Brussels, Belgium).

url:                 http://maty974.github.io
baseurl:             ''
paginate:            5

# Comments are powered by disqus
comments: false

tracking_id: UA-69243698-7 # GA Tracking ID

# About/contact
author:
  name:              Matthieu Cadet
  url:               http://maty974.github.io
  email:             matthieu.cadet@gmail.com

# Custom vars
version:             1.0.0

twitter_username: maty974

github_repo: maty974.github.com
github_username: maty974
#facebook_id: yourusername
