# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems:
  - jekyll-paginate

# Setup
title:               fabic
tagline:             'Random (binary) wanderings in the philament empire'
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
description:         'Just killing time, coding...'
url:                 http://fabic.net
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Fabien Cadet
  url:               https://twitter.com/FabienKd
  email:             cadet.fabien@gmail.com

# Custom vars
version:             1.0.0
