# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

gems:
  - jekyll-paginate
  - jekyll-sitemap

# Setup
title:               Maty<span class="run-974">974</span>
tagline: |
    Senior Compositing Artist,
    Technical Director
    & Pipeline Developer

description: |
    Senior Compositing Artist, Technical Director & Pipeline Developer
    at <a href="http://nWave.com" target="_blank">nWave Digital</a> (Brussels, Belgium).

url:                 http://maty974.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matthieu Cadet
  url:               http://maty974.github.io
  email:             matthieu.cadet@gmail.com

# Custom vars
version:             1.0.0
